name: CI

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: CI 빌드
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: 안드로이드 SDK 설치
        uses: android-actions/setup-android@v2

      - name: gradle 권한 설정
        run: chmod +x gradlew

      - name: local.properties 생성
        run: |
          echo "# DEMO" > local.properties

      - name: Gradle 빌드 시작
        run: ./gradlew :app:build --stacktrace

      - name: Lint report 업로드
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html
          retention-days: 2 # 2일간 보관

      - name: 슬랙 알람 전송
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'Blocker CI'
          fields: repo, message, author, action, eventName, ref, workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}