name: Publish

on:
  release:
    types: [ released ]
  workflow_dispatch:
    inputs:
      version_name:
        description: 'The version name for the tag'
        required: true
        default: 'Unknown'

jobs:
  publish:
    name: 배포
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: gradle 권한 설정
        run: chmod +x gradlew

      - name: MavenCentral 게시
        run: |
          ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: 태그 생성
        if: success()  # 배포가 성공하면 실행
        run: |
          git tag ${{ github.event.inputs.version_name }}
          git push origin ${{ github.event.inputs.version_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}